### PR TITLE
Merge v0.2.0 to scalardl branch and update Scalar DL Node Client SDK 

### PR DESCRIPTION
**Pull request by jnmt**
This patch set merges v0.2.0 from the upstream repository and then update Scalar DL Node Client SDK to v2.0.0. The following two commits are ours.

Update Scalar DL adapter for v0.2.0
https://github.com/scalar-labs/caliper/pull/3/commits/7a7cc1592d0ec57ff6e2ff4b5f13f9fcd3a62f99

Update Scalar DL Node Client SDK to 2.0.0
https://github.com/scalar-labs/caliper/pull/3/commits/72af6649c71fd0c5eebd5b69c7a852c1120bcdfd

Note that the sample workloads, contracts and network configuration files in caliper-samples directory will be moved to the caliper-benchmarks repository before v0.3.0 (not tagged/released yet). So I will move Scalar DL samples to caliper-benchmarks repository soon.
https://github.com/hyperledger/caliper-benchmarks

### CODE REVIEW

**Review by feeblefakie — COMMENTED** [review]
Overall looking great ! Thank you.
Left minor comments.

**Comment by jnmt** [comment]
@feeblefakie Thank you for your kind review.

> Just wondering the reason why `async` is removed.

To be honest, I'm not really sure but it was also removed in Fabric adapter and benchmark fails unless it is removed.

> 2019 -> 2020 for the Copyright ?

I guess that the initial date should not be removed so modified it "2019, 2020".

**Review by feeblefakie — APPROVED** [review]
LGTM !

**Comment by feeblefakie** [comment]
@yito88 I will merge it for now but please take a look when you are back 🙇

**Pull request merged**
